name: Publish Package to npmjs

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '8.9.4'
          registry-url: 'https://registry.npmjs.org'
          scope: '@tracing-zipkin-angular'
      - run: yarn
      - run: yarn build:libs
      - run: cp README.md dist/libs/zipkin && cd dist/libs/zipkin && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
